project:
  type: book
  output-dir: docs

book:
  title: "Environmental variation and extra-pair paternity in birds: a global comparative meta-analysis"
  subtitle: "A reproducible workflow for a global comparative analysis"
  author: "Aneta Arct, Santiago Ortega, Agnieszka Gudowska, Karolina Skorb, Monika Gronowska, Magdalena Zagalska-Neubauer, Dorota Kotowska, Szymon M. Drobniak, Malgorzata Lagisz, Shinichi Nakagawa"
  date: today
  chapters:
    - index.qmd
    - 00_environmental_data_sources.qmd
    - 01_data_preparation.qmd
    - 02_taxonomy_matching.qmd
    - 03_overall_model.qmd
    - 04_pca_for_environmental_predictors.qmd
    - 05_location_scale_models.qmd
    - 06_sensitivity_models.qmd
    - 07_location_scale_models.qmd
    - 07_figures.qmd
  sidebar:
    style: docked
    collapse-level: 1

execute:
  message: false
  warning: false

format:
  html:
    toc: true
    toc-depth: 3
    number-sections: true
    code-fold: true
    code-tools: true
    code-summary: "Show code"